// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2zF5tuRhwPeNSZcG0BfCuB4k_h71LOq8',
    appId: '1:455883017791:web:6103548523c6c3a872328a',
    messagingSenderId: '455883017791',
    projectId: 'fir-notifications-8e9e8',
    authDomain: 'fir-notifications-8e9e8.firebaseapp.com',
    storageBucket: 'fir-notifications-8e9e8.firebasestorage.app',
    measurementId: 'G-L9VJNXXM1C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNIAtUbY6t4Uz8YwtWhV1XJbkxn8CzDHA',
    appId: '1:455883017791:android:92085fdc9bc9bff272328a',
    messagingSenderId: '455883017791',
    projectId: 'fir-notifications-8e9e8',
    storageBucket: 'fir-notifications-8e9e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoNfTwtcMI-Y0MOYADuaRGRMH-sxRvwYk',
    appId: '1:455883017791:ios:fc1b3db32a3e352e72328a',
    messagingSenderId: '455883017791',
    projectId: 'fir-notifications-8e9e8',
    storageBucket: 'fir-notifications-8e9e8.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseNotifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoNfTwtcMI-Y0MOYADuaRGRMH-sxRvwYk',
    appId: '1:455883017791:ios:fc1b3db32a3e352e72328a',
    messagingSenderId: '455883017791',
    projectId: 'fir-notifications-8e9e8',
    storageBucket: 'fir-notifications-8e9e8.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseNotifications',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2zF5tuRhwPeNSZcG0BfCuB4k_h71LOq8',
    appId: '1:455883017791:web:b3be7a2f89f74d2772328a',
    messagingSenderId: '455883017791',
    projectId: 'fir-notifications-8e9e8',
    authDomain: 'fir-notifications-8e9e8.firebaseapp.com',
    storageBucket: 'fir-notifications-8e9e8.firebasestorage.app',
    measurementId: 'G-YYNF2BDR0G',
  );
}
